Refactoring for more compatible among various OSs

diff --git a/mktemp b/mktemp
--- a/mktemp
+++ b/mktemp
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 
 ######################################################################
 #
@@ -6,48 +6,73 @@
 #
 # USAGE: mktemp [--by-myself] [options] [template [...]]
 #
-#        "--by-myself" ..... (write as the 1st argument when use)
+#        --by-myself ..... (write as the 1st argument when use)
 #                            Not use the "built-in" mktemp command
 #                            and always do mktemp by myself but it is
 #                            inferior to the built-in in performance
-#        "-d" .............. Make a directory instead of a file
-#        "-p [DIR]" ........ Define the temporary directory instead of
-#                            $TMPDIR
-#        "-q" .............. Quiet even if some error occurred
-#        "-u" .............. Make a file but remove it immediately
-#        "-t" .............. Add the temporary directory as a prefix
-#                            in front of the filepath
-#        "--suffix=<suff>" . Add the suffix behind the filename
+#        -d .............. Makes a directory instead of a file
+#        -p <DIR> ........ Defines the temporary directory instead of
+#                          $TMPDIR
+#        -q .............. Quiet even if some error occurred
+#        -u .............. Makes a file but remove it immediately
+#        -t .............. Adds the temporary directory as a prefix
+#                          in front of the filepath
+#        --suffix=<suff> . Adds the suffix behind the filename
 #
-# Written by Rich Mikan (richmikan[at]richlab.org) on 2017-01-31
+# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2020202017-05-02
 #
-# This is a public-domain software (CC0). It measns that all of the
+# This is a public-domain software (CC0). It means that all of the
 # people can use this for any purposes with no restrictions at all.
-# By the way, I am fed up the side effects which are broght about by
-# the major licenses.
+# By the way, We are fed up with the side effects which are brought
+# about by the major licenses.
 #
 ######################################################################
- 
-# print the usage and exit
-print_usage_and_exit () {
-  cat <<-__USAGE 1>&2
-	Usage   : ${0##*/} [--by-myself] [options] [template [...]]
-	        : "-d" "-p [DIR]" "-q" "-u" "-t" "--suffix=<suff>"
-	Version : 2017-01-31 14:09:25 JST
-__USAGE
-  exit 1
-}
 
 
-# ===== PREPARATION ==================================================
+######################################################################
+# Initial Configuration
+######################################################################
 
-# --- initialize -----------------------------------------------------
+# === Initialize shell environment ===================================
 set -u
 umask 0022
 export LC_ALL=C
-export PATH="$(command -p getconf PATH):${PATH:-}"
+export PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
+export UNIX_STD=2003  # to make HP-UX conform to POSIX
 
-# --- set the temporary directory ------------------------------------
+# === Define the functions for printing usage and error message ======
+print_usage_and_exit () {
+  cat <<-USAGE 1>&2
+	Usage   : ${0##*/} [--by-myself] [options] [template [...]]
+	Arg&Opts: Almost compatible with GNU mktemp
+	          The following options are available and compatible with it
+	            -d, -p <DIR>, -q, -u, -t, --suffix=<suff>
+	          But --by-myself is the only original option, it prevent
+	          from use the built-in same name command even if available
+	Version : 2020202017-05-02 21:11:01 JST
+	          (POSIX Bourne Shell/POSIX commands)
+	USAGE
+  exit 1
+}
+error_exit() {
+  ${2+:} false && echo "${0##*/}: $2" 1>&2
+  exit $1
+}
+
+# === Exec the built-in mktemp command if OK and exists ==============
+by_myself=0
+case "${1:-}" in 
+  '--by-myself')
+     shift; by_myself=1
+     ;;
+  *) case "$(d=${0%/*}/;[ "_$d" = "_$0/" ]||cd "$d";echo "$(pwd)/${0##*/}")" in
+       "$(command -v mktemp 2>/dev/null)") by_myself=1;;
+     esac
+     ;;
+esac
+case $by_myself in 0) exec mktemp ${1+"$@"}; exit 1;; esac
+
+# === Investigate the temporary directory if set =====================
 Dir_tmp=$(set | grep ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
 case "$Dir_tmp" in
   '') Dir_tmp='/tmp'      ;;
@@ -55,25 +80,25 @@ case "$Dir_tmp" in
   *)  Dir_tmp=${Dir_tmp%/};;
 esac
 
-# --- misc -----------------------------------------------------------
+# === Misc definitions ===============================================
 chrs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_'
 max_retry_when_failed=10
 LFs=$(printf '\\\n_');LFs=${LFs%_}
 
-# --- exec the mktemp command if exists ------------------------------
-case "${1:-}" in
-  --by-myself) shift                                                        ;;
-  *)           type mktemp >/dev/null 2>&1 && { exec mktemp "$@"; exit 1; } ;;
-esac
 
+######################################################################
+# Parse Arguments
+######################################################################
 
-# ===== OPTION PARSING ===============================================
-
+# === Get the options and the filepath ===============================
+# --- initialize option parameters -----------------------------------
 optd=0
 optu=0
 optq=0
 optt=0
 opts=''
+#
+# --- get them -------------------------------------------------------
 optmode=''
 while [ $# -gt 0 ]; do
   case $# in 0) break;; esac
@@ -114,15 +139,11 @@ while [ $# -gt 0 ]; do
     *)  s=$1                                         ;;
   esac
   case "$optmode" in
-    p) [ -d "$s" ] || {
-         printf '%s\n' "${0##*/}: Invalid path by -p,--tmpdir option" 1>&2
-         exit 1
-       }
+    p) [ -d "$s" ] || error_exit 1 'Invalid path by -p,--tmpdir option'
        Dir_tmp=${s%/}; [ -n "$Dir_tmp" ] || Dir_tmp='/.'
        optmode=''; shift; continue        ;;
     s) { printf '%s' "$s" | grep -q '/'; } && {
-         printf '%s\n' "${0##*/}: Invalid suffix option" 1>&2
-         exit 1
+         error_exit 1 'Invalid suffix option'
        }
        opts=$s
        optmode=''; shift; continue        ;;
@@ -130,6 +151,10 @@ while [ $# -gt 0 ]; do
   break
 done
 
+
+######################################################################
+# Prepare for the Main Routine
+######################################################################
 
 # ===== FUNC: random string generator ================================
 # arg   : $1=length
@@ -181,12 +206,18 @@ random_string () {
 }
 
 
-# ===== MAKING LOOP ==================================================
+######################################################################
+# Main Routine
+######################################################################
 
 case $# in 0) optt=1; set -- 'tmp.XXXXXXXXXX';; esac
 
 err=0
 for arg in "$@"; do
+
+  # --- Make dir string for printing ---------------------------------
+  Dir_trg=${arg%/*}
+  case "$Dir_trg" in "$arg") Dir_trg='';; *) Dir_trg="$Dir_trg/";; esac
 
   n=$max_retry_when_failed
   while [ $n -ge 0 ]; do
@@ -236,9 +267,9 @@ for arg in "$@"; do
     break
   done
 
-  # --- print error message when failed to make a file ---------------
+  # --- Print error message when failed to make a file ---------------
   case "${optq}${n}" in
-    '0-1') printf '%s\n' "${0##*/}: failed on $Path_target" 1>&2
+    '0-1') printf '%s\n' "${0##*/}: failed on $Dir_trg${Path_target##*/}" 1>&2
            err=1
            continue
            ;;
@@ -247,15 +278,17 @@ for arg in "$@"; do
            ;;
   esac
 
-  # --- print the path of the file -----------------------------------
-  printf '%s\n' "$Path_target"
+  # --- Print the path of the file -----------------------------------
+  printf '%s%s\n' "$Dir_trg" "${Path_target##*/}"
 
-  # --- remove the file if -u,--dry-run option is set ----------------
+  # --- Remove the file if -u,--dry-run option is set ----------------
   case $optu in 1) rm -rf "$Path_target";; esac
 
 done
 
 
-# ===== EXIT =========================================================
+######################################################################
+# Finish
+######################################################################
 
 exit $err
